### ISSUE TITLE
error when serving connection: body size exceeds the given limit

### ISSUE THREAD

**Issue by skolodyazhnyy** [tpbowden/swarm-ingress-router#22]
Hey,

I'm using this router to serve multiple applications in my docker swarm, it works OK. But the moment I tried to set-up docker registry I run into an issue with body size limits.

I dig a little bit into it and I saw you are using `valyala/fasthttp` package to proxy traffic from router to service endpoint. By default it has request body limit of 4 MB which is clearly not enough for Docker Registry.

Do you think it make sense to have a label with body size limit? Or may be at least a flag for console application to control body limit? Or may be set it to unlimit and control limits on the application side.

Let me know what do you think, I may find some time to do a pull request.

**Comment by tpbowden** [comment]
Makes sense to have this configurable to allow unlimited upload size but since most people don't want to have to handle this in their app and probably aren't going to also put nginx in front of their app behind the proxy it will probably stay is it is by default. 

My thoughts for how it could work is command line args to the router service, something like --max-body-size=[size in MB or 0 for unlimited]

**Comment by tpbowden** [comment]
Did the changes you made fix the problem? If so I can close this issue

**Comment by christoph-hipp** [comment]
It looks like that --max-body-size=0 does not work --max-body-size=300 works. 
I tested with dev tag on dockerhub.

**Comment by tpbowden** [comment]
No --max-body-size=0 was not implemented as it would be a very large risk for DOS attacks if you don't restrict max body size at all and as such isn't supported by fasthttp.
